name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: semantic-release
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: install dependencies
        run: poetry install

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
          # npx --yes \
          #   -p semantic-release \
          #   -p "@semantic-release/commit-analyzer" \
          #   -p "@semantic-release/release-notes-generator" \
          #   -p "@semantic-release/changelog" \
          #   -p "@semantic-release/github" \
          #   -p "@semantic-release/git" \
          #   semantic-release --ci
